### ISSUE TITLE
Missing Pre-trained weight files

### ISSUE THREAD

**Issue by AshwinRaikar88** [sid0312/ANPR#1]
Hello could you please upload the pre-trained weight files in google drive
Thanks

**Comment by AshwinRaikar88** [comment]
This repository is over its data quota. Purchase more data packs to restore access
I got this error while trying git lfs pull.

$ git lfs pull
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/sid0312/ANPR.git/info/lfs'

**Comment by sid0312** [comment]
It literally took min 38 min to train for 100 epochs. please train it on
your own.
